<!doctype html>
<html>
<head>
<meta charset="utf-8">

<!-- Edit to select which version is desired 3.3.4 or 3.5  -->

<script type="text/javascript" src="/brython3.5/brython.js"></script>
<script type="text/javascript" src="/brython3.5/brython_stdlib.js"></script>

<script>
    Namespace = {};

    Namespace.MyError = function (message) {
        var output = document.getElementById('print-output');
        try{
            if (__BRYTHON__.__MAGIC__ == "3.3.4") {
                return window.MyException_en(message);
            } else {
                return __BRYTHON__.$call(window.MyException_en)(message);
            }
        } catch (e) {
            output.innerHTML += "Should not have reached this point";
        }
    };

    function run_py(ev) {
        var src = document.getElementById('source').innerText;
        var output = document.getElementById('print-output');
        Namespace.cached_exception = undefined;
        output.innerHTML = '';

        try {
            eval_py(src);
            if (Namespace.cached_exception) { // rethrow to process at the JS layer
                throw Namespace.cached_exception;
            }
        } catch (e) {
            output.innerHTML += e.__name__ + ": ";
            output.innerHTML += e.custom_message;
        }
    }

    function run_second_example (ev) {
        var src = document.getElementById('second-example').innerText;
        var output = document.getElementById('print-output');
        output.innerHTML = '';
        eval_py(src);
    }

    function create_js_exception() {
        throw new Namespace.MyError("Happily creating an exception")
    }
</script>



<script id="python_script" type="text/python">
    import sys
    from browser import document, window

    def _write(*args):
        document["print-output"].html += ''.join(args)

    sys.stdout.write = _write

    class MyException(Exception):
        def __init__(self, message):
            self.custom_message = message;
            super().__init__(message)
    window['MyException_en'] = MyException

    def create_exception() :
        window.create_js_exception()

    def eval_py(src):
        window.console.dir(window.Namespace)
        try:
            exec(src)
        except Exception as e:
            window.Namespace.cached_exception = e
    window['eval_py'] = eval_py

    print("Brython version used:", __BRYTHON__.__MAGIC__)
</script>


<style>
  p, pre {
    max-width: 800px;
  }
  pre#print-output {
      background: antiquewhite;
  }
  button {
    margin: 20px;
    padding: 10px;
  }

</style>

</head>

<body onload="brython(1)">

<p>
    Attempting to create an <b>absolute</b> minimal working example that reproduces
    the type of error seen in Reeborg when using Brython 3.5.0rc1 and
    which was not present when using Brython 3.3.4.

    Edit the html file to select the desired version to run the tests.
    <br>
    Once this example works, test the slightly more convoluted one which is
    closer to the code I run, and can be used to compare running Javascript and
    Python examples.
</p>

<p><button onclick="run_py()">Exec Python</button>
    <button onclick="run_second_example()">Second example</button>
</p>

<pre id="source" contenteditable="true">
create_exception()
</pre>

<pre id="print-output"></pre>

<pre id="second-example" contenteditable="true">
class MyOtherException(Exception):
    pass

try:
    raise MyOtherException()
except MyOtherException:
    print("Ok, MyOtherException caught")
except BaseException:
    print("Wrong, BaseException caught")

try:
    create_exception()
except MyException:
    print("Ok, MyException caught")
except BaseException:
    print("Wrong, BaseException caught")

</pre>

</body>

</html>